# fly.toml app configuration file generated for spotify-playlists on 2024-12-19T00:00:00Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "likes-song"
primary_region = "ord"

[build]

[env]
NODE_ENV = "production"

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 256

[deploy]
release_command = "echo 'Deploying likes-song'"
